version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.9 /usr/local/share/virtualenvs/tap-bigcommerce
            source /usr/local/share/virtualenvs/tap-bigcommerce/bin/activate
            uv pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-bigcommerce/bin/activate
            pylint tap_bigcommerce -d C,R,W
      - add_ssh_keys
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-bigcommerce/bin/activate
            uv pip install pytest coverage
            coverage run -m pytest tests/unittests
            coverage html
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
